OAM-218: Many program ids for GET API for orderables.
OpenLMIS/openlmis-referencedata pull request #109
Opened 2024-06-25 10:57 UTC by tsznaj

2024-06-25 10:57 UTC, tsznaj commented
Integration tests have still to be fixed.

2024-06-25 11:41 UTC, sradziszewski commented on src/main/java/org/openlmis/referencedata/web/OrderableSearchParams.java
> +    return Collections.singleton(programCode);
should it always be like that (returning singleton?)

2024-06-25 12:47 UTC, tsznaj commented on src/main/java/org/openlmis/referencedata/web/OrderableSearchParams.java
> +    return Collections.singleton(programCode);
I think so, as we are not supposed to change POST search endpoint, where we can get still only one program code.
Or maybe we should change it to have the ability to pass many program codes to POST search endpoint as well?

2024-06-26 12:32 UTC, pwargulak requested changes
Left some questions

2024-06-26 12:32 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/repository/custom/impl/OrderableRepositoryImpl.java
> +            .in(getProgramCodesLowerCase(searchParams)));
Use `programCodes` from few lines above.

2024-06-26 12:32 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/repository/custom/impl/OrderableRepositoryImpl.java
> +      if (null != searchParams.getProgramCodes()) {
Very similar pattern is in `org.openlmis.referencedata.repository.custom.impl.OrderableRepositoryImpl#prepareParams` too - make them consistent. 
Consider moving `null != searchParams.getProgramCodes()` to the `getProgramCodesLowerCase` method.

2024-06-26 12:32 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/repository/custom/impl/OrderableRepositoryImpl.java
> +      joiner.add(builder.toString());
Not a request to change, but I'm almost sure the more convenient syntax: `"'" + programCode + "'"` is going to be optimzied to StringBuilder (or better).

2024-06-26 12:32 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/web/OrderableSearchParams.java
> +    return Collections.singleton(programCode);
So `OrderableSearchParams` supports search by single programCode, but it implements `OrderableRepositoryCustom.SearchParam` which supports multiple `programCodes`. The `getProgramCodes` is part of `OrderableRepositoryCustom.SearchParam` contract, and is JsonIgnore becacuse there is no `programCodes` property, no setter to call when serializing/deserializing.

Hmm, makes sense.

2024-06-26 14:03 UTC, sradziszewski approved these changes
nothing from me except Piotr's comments

2024-06-26 15:44 UTC, merged

2024-06-26 15:45 UTC, tsznaj commented
Piotr cannot technically approve now here - but he has approved.