AO-871: Added IntegrationEmail entity with CRUD and db migration
OpenLMIS/openlmis-referencedata pull request #116
Opened 2024-07-10 12:20 UTC by sradziszewski

JIRA task link: https://openlmis.atlassian.net/browse/AO-871

2024-07-10 13:55 UTC, tsznaj commented on docker-compose.yml
> +      - "5005:5005"
That was added here accidentally, I think :)

2024-07-10 13:55 UTC, tsznaj commented on package-lock.json
That was added here accidentally, I think :)

2024-07-10 14:11 UTC, tsznaj commented on src/main/java/org/openlmis/referencedata/repository/IntegrationEmailRepository.java
> +      + "            INNER JOIN referencedata.jv_global_id g "
no newline character here - can it be like this?

2024-07-10 16:32 UTC, sradziszewski commented on docker-compose.yml
> +      - "5005:5005"
I removed these lines.

2024-07-10 16:40 UTC, sradziszewski commented on src/main/java/org/openlmis/referencedata/repository/IntegrationEmailRepository.java
> +      + "            INNER JOIN referencedata.jv_global_id g "
I copied all this code from another class, and I see that it's the same in other classes, so it's not a problem. I'll leave it as is.

2024-07-11 08:18 UTC, tsznaj commented on src/main/resources/db/migration/20240710090354134__add_integration_emails_table.sql
Do we need primary key here?

2024-07-11 08:43 UTC, tsznaj requested changes
Added one comment.

2024-07-11 08:57 UTC, sradziszewski commented on src/main/resources/db/migration/20240710090354134__add_integration_emails_table.sql
I added primary key constraints.

2024-07-12 10:32 UTC, merged