SELV3-781: Backend for catchment population calculation
OpenLMIS/openlmis-referencedata pull request #134
Opened 2024-12-12 14:52 UTC by druchniewicz

2024-12-12 15:19 UTC, pwargulak requested changes
Please take a look at calculation

2024-12-12 15:19 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +    if (shouldCatchmentPopulationBePerformed(parent, allLevels)) {
I guess it might be a lot, but we can save some performance if `catchmentPopulationAutoCalc` check would be the first thing that happens in the method and ends it quickly. Now, regardless of the `catchmentPopulationAutoCalc` value we ru the read query.

2024-12-12 15:19 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +      Optional<GeographicLevel> childLevel = allLevels.stream()
I can't understand this algorithm.

Why it is not only:
1. When GeoZone A is changed.
2. An update calc is called on it's parent.
3. The parent's population is updated to the sum of its children's populations (single DB query, Spring's repo query method).

It will never be called on childless parent.
It can be called on the root geozone -> then parent is null -> then handle null as Do-Nothing.
It should not care about the level.
We do rely on the recursive action, tree traversal, that an update to GeoZone Parent will cause an update to Parent of GeoZone Parent. 

I'm not sure, but I would expect that changing a population in geo zone at lowest level, will cause the precaution for parent, parent's parent, till the root of the gezone hierarchy.

2024-12-12 19:22 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +      Optional<GeographicLevel> childLevel = allLevels.stream()
this is exactly how it should work. I corrected logic, there was a part of if condition wrong

2024-12-13 09:46 UTC, pwargulak requested changes
See comments

2024-12-13 09:46 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +      Optional<GeographicLevel> childLevel = findChildLevel(parent);
Hmm, I think I see what you meant, but a case when we have configured a hierarchy using GeographicZone.parent reference that does have GeographicLevel on different "levels" is a wrong config. 
Also, I think since the child-parent relation is defined by GeographicLevel.parent, then all children should be included, not only children which share the same GeographicLevel.

I would remove the level check completely and do only `repo.findByParent(parent)`, moreover I would just add tailored [query](https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html#jpa.query-methods.at-query) to the repo service that makes `select sum(pop) from zone where parent`

2024-12-13 09:46 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/export/GeographicZonesImportPersister.java
> +    List<GeographicLevel> allLevels = StreamSupport.stream(geographicLevelRepository.findAll()
This is going to be performance bottleneck - a findAll for each row - maybe it will be optimized and Hibernate will not make a query everytime, but I would not count on it.

2024-12-13 09:46 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/export/GeographicZonesImportPersister.java
> +  private void validateZone(GeographicZone zone) {
This validation - if you thnk is needed (I would not add it) -  must apply only if automatic calc is enabled.

2024-12-13 11:51 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +    return childLevel == lowestLevelNumber && catchmentPopulationAutoCalc;
not valid anymore

2024-12-13 11:51 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +  private int sumCatchmentPopulation(List<GeographicZone> geoZones) {
fixed

2024-12-13 11:51 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/aspect/CatchmentPopulationAspect.java
> +      Optional<GeographicLevel> childLevel = findChildLevel(parent);
fixed

2024-12-13 11:51 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/service/export/GeographicZonesImportPersister.java
> +    List<GeographicLevel> allLevels = StreamSupport.stream(geographicLevelRepository.findAll()
fixed

2024-12-13 11:52 UTC, druchniewicz commented on src/main/java/org/openlmis/referencedata/service/export/GeographicZonesImportPersister.java
> +  private void validateZone(GeographicZone zone) {
it has been implemented because if user can only edit the lowest level in geo zones hierarchy then it should work the same way via zip import

2024-12-13 12:31 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/export/GeographicZonesImportPersister.java
> +    int lowestLevelNumber = Collections.max(geoLevels,
Hmm, can this be calculated once?

2024-12-13 12:32 UTC, pwargulak requested changes
PLease look at the last comment :)

2024-12-13 12:54 UTC, pwargulak approved these changes
Good enough.

2024-12-13 12:55 UTC, merged