OLMIS-7644: Added csv export functionality
OpenLMIS/openlmis-referencedata pull request #45
Opened 2023-01-25 08:44 UTC by sradziszewski

Description of requirements for this PR available for viewing on JIRA in [this ticket](https://openlmis.atlassian.net/browse/OLMIS-7644).

2023-01-25 11:20 UTC, pwargulak requested changes

2023-01-25 11:20 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataExportService.java
> +    setFormat(format);
This is generally bad idea. 
The instance of DataExportService (and any other Service) can be accessed by multiple threads - e.g.: when different users requests the export at the same time. 
In this specific case, it might work because how often you'll get two users doing the same at the same time, but still it's not a good practice.

Passing the 'format' down to all methods, or in other cases passing another variables down as method parameters is not nice solution too. You'll get methods with a lot of args, but still it's safe from risk of multi threading issues. In case of DataExportService you'll probably get away with just passing format down as argument.

The better solutions which I've seen are:
1. Having a private static class SomthingContext which holds all initial input information or/and intermediate data - that way you'll pass only SomthingContext ctx down as argument and methods pull what they need.
2. Refactoring the code of service to use 'builder-style' logic. Where you have new class, e.g.: DataExporter, and do something like: new DataExport(format, filenames).export();

2023-01-25 11:20 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataExportService.java
> +    DataFormatterService formatter;
Declaring variables at the beginning, was it 'the way' in C I think?
I think there is no readability benefit to do it, just declare variable at the time when you define it - unless you need to declare if beforehand.

The 'output' also looks misleading in my opinion, it could be returned directly from the try-catch. Now it kind of suggests to me that there is some default value for the 'output' which will be used only when try-catch fails or maybe there is some more logic after try-catch, but then I look at try-catch and it either goes OK and sets the output's value, or fails and the method ends with exception.

2023-01-31 07:17 UTC, sradziszewski commented on src/main/java/org/openlmis/referencedata/service/DataExportService.java
> +    setFormat(format);
based on the referencedata code, I created a wrapper in the form of a parameter class.

2023-01-31 07:17 UTC, sradziszewski commented on src/main/java/org/openlmis/referencedata/service/DataExportService.java
> +    DataFormatterService formatter;
Moved variables and return statements to 'try' blocks, where possible I used try-with-resources.

2023-01-31 07:17 UTC, sradziszewski commented
I made changes as suggested, please note that I changed ExportableDataRepository to ExportableDataService because some files (including future ones) may not be referencedata entities.

2023-01-31 07:37 UTC, NikolaLaskowska commented
Please update the changelog

2023-01-31 14:34 UTC, anawrotsoldevelo approved these changes

2023-02-02 15:16 UTC, pwargulak approved these changes
Looks fine

2023-02-02 20:41 UTC, merged