OLMIS-7672: Orderables import
OpenLMIS/openlmis-referencedata pull request #67
Opened 2023-08-22 14:04 UTC by anawrotsoldevelo

2023-08-25 09:01 UTC, pwargulak commented
@anawrotsoldevelo Sonar seems to be failing: http://sonar.openlmis.org/dashboard?id=org.sonarqube%3Aopenlmis-referencedata%3AOLMIS-7672

2023-08-25 09:45 UTC, anawrotsoldevelo commented
I fixed sonar issues but the report has not been refreshed for the whole branch. 
Here is the most recent report: [](http://sonar.openlmis.org/dashboard?id=org.sonarqube%3Aopenlmis-referencedata%3APR-67)
@pwargulak

2023-08-25 10:59 UTC, pwargulak requested changes
I left some comments, plus the Sonar had some issues.

2023-08-25 10:59 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +      if (latestOrderable == null) {
If-else looks strange - like why not just:
`orderableBuilder.newOrderable(orderableDto, latestOrderable);`
since the null in 2nd arg is allowed.

2023-08-25 10:59 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +    List<Orderable> persistList = new ArrayList<>();
The creation of `persistList` could be moved to separate method, so `processOrderables` would look like:
```
List<OrderableDto> importedDtos = readCsv(OrderableDto.class, dataStream);
return createOrderables(importedDtos);
```

2023-08-25 10:59 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +    ModelClass<T> model = new ModelClass<>(clazz);
I think this is a case of preference, but in Java you don't need to declare variables at the top of method (like in old C). I prefer to declare variables close to the place they are  used. 
In this case, `model` would be declared directly before reader.

It's not a change request, more like a comment/observation.

2023-08-25 10:59 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/OrderableService.java
> +  public List<OrderableDto> findAll() {
I have one concern about this method and the `ExportableDataService` interface.
You've got `OrderableService` which works on `Orderable` entity. And, now this service has `findAll` method, I would assume this method returns `Orderable`, but it does return `OrderableDto`.
I imagine using `OrderableDto` instead `Orderable` for exporting had some reason, so I think maybe a `findAll` method in `ExportableDataService` should be renamed.
Maybe something:
```
public interface ExportableDataService<T> {
  List<T> findAllExportableItems();
  Class<T> getExportableType();
}
```

2023-08-25 10:59 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/util/FileHelper.java
> +        throw new ValidationMessageException(MessageKeys.ERROR_IO);
Would be nice to have some message to give context for this exception.
```
throw new ValidationMessageException(MessageKeys.ERROR_IO, "empty archive");
```

2023-08-30 08:29 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +      if (latestOrderable == null) {
Changed it to one-liner, as you've suggested

2023-08-30 08:30 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +    List<Orderable> persistList = new ArrayList<>();
I extracted mentioned code to separate function

2023-08-30 08:31 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +    ModelClass<T> model = new ModelClass<>(clazz);
Good point, I moved this variable

2023-08-30 08:32 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/OrderableService.java
> +  public List<OrderableDto> findAll() {
I changed the naming

2023-08-30 08:32 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/util/FileHelper.java
> +        throw new ValidationMessageException(MessageKeys.ERROR_IO);
Fixed

2023-09-01 06:52 UTC, sradziszewski approved these changes

2023-09-11 08:51 UTC, merged