OLMIS-7757: Program Orderables import
OpenLMIS/openlmis-referencedata pull request #70
Opened 2023-09-12 11:23 UTC by anawrotsoldevelo

2023-09-14 09:47 UTC, pwargulak requested changes
Left a comment.

2023-09-14 09:47 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +      } else if (entry.getKey().equals(PROGRAM_ORDERABLE_CSV)) {
A bigger suggestion here. 
The DataImportService class handles concerns: read ZIP file, decides what kind of CSV it is (what data is inside), performs import for Orderable and performs import of ProgramOrderable.
I think it would be good idea to decouple this class.

Suggestion:

- New DataImportPersister interface (name can be changed). Single method: processAndPersist(InputStream dataStream);
- New OrderableImportPersister class implements DataImportPersister, basically a class with the current processAndPersistOrderables method.
- New  ProgramOrderableImportPersister class implements DataImportPersister, basically a class with the current processAndPersistProgramOrderables method.
- the DataImportService picks the implementation of DataImportPersister. You could implement the ProgramOrderableImportPersister and OrderableImportPersister as Spring beans, named, name would equal to the filename (e.g.: ProgramOrderableImportPersister = "programOrderable.csv"), inside DataImportService you would just use `beanFactory.getBean(entry.getKey(), DataImportPersister.class).processAndPersist(entry.getValue());` (plus handling when there is no bean for the CSV file). You can also preload the list of beans for CSV files using: https://www.baeldung.com/spring-dynamic-autowire#autowire-interface

The benefit is that, you have a classes which handles single concerns (ProgramOrderableImportPersister persists ProgramOrderable only), so in case you need to add new CSV file - you add a new bean and don't modify existing code.

2023-09-21 11:26 UTC, pwargulak approved these changes
Left a question - if there is `null` then please handle the `null`.

2023-09-21 11:26 UTC, pwargulak commented on src/main/java/org/openlmis/referencedata/service/export/DataImportService.java
> +          beanFactory.getBean(entry.getKey(), DataImportPersister.class);
Just to make sure - `getBean` throws any exception if the bean is not found or returns null?

2023-09-22 09:26 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/export/DataImportService.java
> +          beanFactory.getBean(entry.getKey(), DataImportPersister.class);
You're right, beanFactory.getBean() is throwing exception instead of returning null, I changed the code to handle this one correctly.

2023-09-22 09:27 UTC, anawrotsoldevelo commented on src/main/java/org/openlmis/referencedata/service/DataImportService.java
> +      } else if (entry.getKey().equals(PROGRAM_ORDERABLE_CSV)) {
I decoupled this class using proposed approach.

2023-09-22 09:31 UTC, merged