CQI-9: use sonarcloud instead of sonarqube
OpenLMIS/openlmis-referencedata pull request #81
Opened 2023-10-30 14:59 UTC by olewandowski1

[CQI-9](https://openlmis.atlassian.net/browse/CQI-9)

Within the context of this ticket, I've implemented a GitHub workflow for static code analysis using SonarCloud. To ensure consistent builds, I upgraded the SonarQube plugin version from 2.6.2 to 3.3 and Lombok from 1.18.10 to 1.18.22. Additionally, I removed the SonarQube stage from the Jenkins pipeline.

2023-10-30 16:02 UTC, dborowiecki requested changes

2023-10-30 16:02 UTC, dborowiecki commented on Jenkinsfile
> -            when {
i think we shouldn't remove this block of code entirely but keep only contract tests

2023-10-31 08:41 UTC, olewandowski1 commented on Jenkinsfile
> -            when {
The name of this stage could be misleading, but I think that this step covers just a SonarQube analysis.

2023-10-31 08:43 UTC, olewandowski1 commented on Jenkinsfile
> -            when {
Nevertheless, I think that in the scope of this PR, I have to delete the `ci-sonarAnalysis.sh` script, which is not used anymore.

2023-11-16 14:02 UTC, dszafranek approved these changes

2023-11-16 14:02 UTC, merged