OAM-186: Added home facility validation for ward/service type
OpenLMIS/openlmis-referencedata pull request #94
Opened 2024-05-29 14:56 UTC by sradziszewski

JIRA task link: https://openlmis.atlassian.net/browse/OAM-186

2024-05-31 07:52 UTC, tsznaj commented on src/test/java/org/openlmis/referencedata/validate/UserValidatorTest.java
> +  public void shouldRejectIfHomeFacilityHasWardOrServiceType() {
Please also add a test where facilityRepository.findById returns empty Optional.

2024-05-31 07:52 UTC, tsznaj requested changes
Please check one comment.

2024-06-03 17:29 UTC, sradziszewski commented on src/test/java/org/openlmis/referencedata/validate/UserValidatorTest.java
> +  public void shouldRejectIfHomeFacilityHasWardOrServiceType() {
I added extra test for that case.

2024-06-03 18:11 UTC, tsznaj approved these changes
Approved!

2024-06-03 18:11 UTC, merged